name: Automatically Update Repository
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  RunScript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
      - name: Load secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Check update
        shell: pwsh
        run: |
          ./Update-Repository.ps1
      - name: Reconfigure script
        if: env.REPO_PAT != ''
        shell: pwsh
        run: |
          ./Modules/Initialize-PostUpdate.ps1
      - name: Commit changes
        shell: pwsh
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update script, $(Get-Date -AsUtc -Format 'yyyy-MM-ddTHH:mm:ssZ')"
          git push
